name: Delete
on:
  schedule:
    - cron: "20 3 * * *"
  workflow_dispatch:      # <--- 加上这一行，就能手动运行了
    # 这里可以留空，也可以按需添加一些输入参数
jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          days-ago: 1 # 删除3天前的运行记录
          keep-latest: 3 # 可选：始终保留最新的5次记录
