name: Delete
on:
  schedule:
    - cron: "20 3 * * *"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete
        uses: GitRML/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          days-ago: 30 # 删除30天前的运行记录
          keep-latest: 5 # 可选：始终保留最新的5次记录
